import AppleTrailersWrapper
import traceback


def test():
    try:
        results = AppleTrailersWrapper.Search("The Hunger Games")
        title = AppleTrailersWrapper.Title(results["results"][0])

        title.get_title_dict()
        title.get_movie_title()
        title.get_title_url()
        title.get_movie_rating()
        title.get_release_date()
        title.get_release_copy()
        title.get_copyright()
        heros = title.get_all_heros()
        heros[0].get_hero_dict()
        heros[0].get_image_url()
        hero = title.get_hero("0")
        hero.get_hero_dict()
        hero.get_image_url()
        local_hero = title.get_locale_hero("en")
        local_hero.get_backgrounds()
        local_hero.get_locale_dict()
        title.get_showtimes()
        title.get_details()
        title.get_details().get_details_dict()
        title.get_details().get_locale("en")
        title.get_details().get_all_locale()
        title.get_details().get_genres()
        title.get_details().get_official_url()
        title.get_details().get_run_time()
        title.get_related()
        for related in title.get_related():
            related.get_all_locale()
            related.get_locale("en")
            related.get_title()
            related.get_item()
            related.get_itunes_link()
            related.get_thumbnail()
            related.get_type()
        title.get_featured()
        title.get_featured().get_thumbnail()
        title.get_featured().get_itunes_link()
        title.get_featured().get_item()
        title.get_featured().get_title()
        title.get_featured().get_locale()
        title.get_featured().get_heading()
        title.get_featured().get_available_date()
        title.get_reviews()
        title.get_reviews().get_average()
        title.get_reviews().get_count()
        title.get_reviews().get_negative()
        title.get_reviews().get_positive()
        title.get_reviews().get_rating()
        title.get_reviews().get_review(0)
        title.get_reviews().get_review(0).get_rating()
        title.get_reviews().get_review(0).get_date()
        title.get_reviews().get_review(0).get_publisher()
        title.get_reviews().get_review(0).get_reviewer()
        title.get_reviews().get_review(0).get_text()
        title.get_reviews().get_reviews_dict()
        title.get_reviews().get_rotten_tomatoes_link()
        title.get_reviews().is_fresh()
        title.get_review(0)
        title.get_review(0).get_text()
        title.get_review(0).get_reviewer()
        title.get_review(0).get_publisher()
        title.get_review(0).get_date()
        title.get_review(0).get_rating()
        for clip in title.get_clips():
            clip.get_title()
            clip.get_thumbnail()
            clip.get_locale("en")
            clip.get_all_locale()
            clip.get_artist()
            clip.get_clip_dict()
            clip.get_faded()
            clip.get_kind()
            clip.get_posted()
            clip.get_runtime()
            clip.get_screenshot()
            clip.get_version("sd")
            clip.get_version("sd").get_clip_version_dict()
            clip.get_version("sd").get_filename()
            clip.get_version("sd").get_height()
            clip.get_version("sd").get_name()
            clip.get_version("sd").get_src()
            clip.get_version("sd").get_src_alt()
            clip.get_version("sd").get_width()
            clip.get_versions()
            for version in clip.get_versions():
                version.get_src_alt()
                version.get_width()
                version.get_src()
                version.get_name()
                version.get_height()
                version.get_filename()
                version.get_clip_version_dict()

        title.get_clip(0)
        title.get_clip(0).get_title()
        title.get_clip(0).get_thumbnail()
        title.get_clip(0).get_locale("en")
        title.get_clip(0).get_all_locale()
        title.get_clip(0).get_artist()
        title.get_clip(0).get_clip_dict()
        title.get_clip(0).get_faded()
        title.get_clip(0).get_kind()
        title.get_clip(0).get_posted()
        title.get_clip(0).get_runtime()
        title.get_clip(0).get_screenshot()
        title.get_clip(0).get_version("sd")
        title.get_clip(0).get_version("sd").get_clip_version_dict()
        title.get_clip(0).get_version("sd").get_filename()
        title.get_clip(0).get_version("sd").get_height()
        title.get_clip(0).get_version("sd").get_name()
        title.get_clip(0).get_version("sd").get_src()
        title.get_clip(0).get_version("sd").get_src_alt()
        title.get_clip(0).get_version("sd").get_width()
        title.get_clip(0).get_versions()
        for version in title.get_clip(0).get_versions():
            version.get_src_alt()
            version.get_width()
            version.get_src()
            version.get_name()
            version.get_height()
            version.get_filename()
            version.get_clip_version_dict()

        print("------------ ALL TESTS PASSED -----------")
    except Exception:
        traceback.print_exc()


test()
